#@ load("@ytt:data", "data")
#@ registry = data.values.tap.credentials.registry
---

apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: "tbs-full-deps-repository"
  namespace: #@ data.values.tap.namespace
spec:
  fetch:
    imgpkgBundle:
             #! for example, harbor.acme.com/tanzu-app-platform/tap-packages:1.3.build.3
      image: #@ "{}/{}:{}".format(registry.host, registry.tbs_deps_repo, data.values.tap.tbs_deps_version)
      secretRef:
        name: tap-registry