#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---


#@ def config():
#@ registry = data.values.tap.credentials.registry
#@  return {
#@    "auths": {
#@      registry.host: {
#@        "username": registry.username,
#@        "password": registry.password
#@      }
#@    }
#@  }
#@ end
---
#! ref: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-how-to-guides-dynamic-provisioning-tanzu-postgresql.html
apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: tanzu-psql-service-instances
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: #@ json.encode(config())