#@ load("@ytt:data", "data")

#! Helpers because typing is hard
#@ domains      = data.values.tap.domains

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ "cnr-{}".format(domains.contour_tls_secret)
  namespace: #@ domains.contour_tls_namespace
spec:
  commonName: #@ "*.{}".format(domains.knative)
  dnsNames:
  - #@ "*.{}".format(domains.knative)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: #@ "cnr-{}".format(domains.contour_tls_secret)
